sudo: false
language: node_js
node_js:
  - "8"

script: "npm test"

jobs:
  include:
    - stage: unit tests
      script:
        - npm test
        - cat test/unit/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

    - stage: deploy artifacts
      script: "npm run docs"
      deploy:
        skip_cleanup: true
        provider: pages
        local_dir: docs
        github_token: $GITHUB_TOKEN
        email: saintplay@gmail.com
        name: Diego Jara
        on:
          branch: master
